# Generated by Django 4.1.7 on 2023-07-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionpost',
            name='description',
            field=models.TextField(),
        ),
    ]
